theme: jekyll-theme-cayman
url : "https://kimjungho86.github.io"
baseurl : ""

title : "테스트 블로그"
title_separator          : "-"
name                     : "Your Name"
description              : "An amazing website."
